package io.vertigo.commons.impl.daemon;

import io.vertigo.commons.daemon.DaemonDefinition;
import io.vertigo.commons.daemon.DaemonStat;
import io.vertigo.lang.Assertion;

/**
 * Snapshot of execution's stats.
 * A snaphot is prefereed to a real time view to avoid complexity generated by "synchronized"
 * @author pchretien
 */
public final class DaemonStatImpl implements DaemonStat {
	private final DaemonDefinition daemonDefinition;
	private final DaemonStat.Status status;
	private final long sucesses;
	private final long failures;

	public DaemonStatImpl(DaemonDefinition daemonDefinition, long successes, long failures, DaemonStat.Status status) {
		Assertion.checkNotNull(daemonDefinition);
		Assertion.checkNotNull(status);
		//-----
		this.daemonDefinition = daemonDefinition;
		this.failures = failures;
		this.sucesses = successes;
		this.status = status;
	}

	@Override
	public DaemonDefinition getDaemonDefinition() {
		return daemonDefinition;
	}

	@Override
	public long getCount() {
		return sucesses + failures;
	}

	@Override
	public long getSuccesses() {
		return sucesses;
	}

	@Override
	public long getFailures() {
		return failures;
	}

	@Override
	public Status getStatus() {
		return status;
	}
}
