package io.vertigo.dynamo.store.data.domain.car;

import io.vertigo.dynamo.domain.model.DtStaticMasterData;
import io.vertigo.dynamo.domain.model.URI;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@javax.persistence.Entity
@javax.persistence.Table(name = "MOTOR_TYPE")
public final class MotorType implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private String mtyCd;
	private String label;

	/** {@inheritDoc} */
	@javax.persistence.Transient
	@Override
	public URI<MotorType> getURI() {
		return DtObjectUtil.createURI(this);
	}

	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'id'.
	 * @return String mtyCd <b>Obligatoire</b>
	 */
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SEQ_MOTOR_TYPE", sequenceName = "SEQ_MOTOR_TYPE", allocationSize = 1)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "SEQ_MOTOR_TYPE")
	@javax.persistence.Column(name = "MTY_CD")
	@Field(domain = "DO_STRING", type = "ID", required = true, label = "id")
	public String getMtyCd() {
		return mtyCd;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'id'.
	 * @param mtyCd String <b>Obligatoire</b>
	 */
	public void setMtyCd(final String mtyCd) {
		this.mtyCd = mtyCd;
	}

	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Label'.
	 * @return String label <b>Obligatoire</b>
	 */
	@javax.persistence.Column(name = "LABEL")
	@Field(domain = "DO_FULL_TEXT", required = true, label = "Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Label'.
	 * @param label String <b>Obligatoire</b>
	 */
	public void setLabel(final String label) {
		this.label = label;
	}

	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
