package io.vertigo.studio.tasktest;

import java.util.Optional;

import javax.inject.Inject;

import io.vertigo.app.Home;
import io.vertigo.dynamo.store.StoreServices;
import io.vertigo.dynamo.task.TaskManager;
import io.vertigo.dynamo.task.metamodel.TaskDefinition;
import io.vertigo.dynamo.task.model.Task;
import io.vertigo.dynamo.task.model.TaskBuilder;
import io.vertigo.lang.Assertion;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DaoPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public DaoPAO(final TaskManager taskManager) {
		Assertion.checkNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Home.getApp().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkOneListParamSelect.
	 * @param input List de Integer
	 * @return Integer result
	*/
	public Integer oneListParamSelect(final java.util.List<Integer> input) {
		final Task task = createTaskBuilder("TkOneListParamSelect")
				.addValue("input", input)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkOneParamSelect.
	 * @param input Integer
	 * @return Integer result
	*/
	public Integer oneParamSelect(final Integer input) {
		final Task task = createTaskBuilder("TkOneParamSelect")
				.addValue("input", input)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkPing.
	 * @return Option de Integer result
	*/
	public Optional<Integer> ping() {
		final Task task = createTaskBuilder("TkPing")
				.build();
		return Optional.ofNullable((Integer) getTaskManager()
				.execute(task)
				.getResult());
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
