package ${dtDefinition.packageName};

import ${dtDefinition.stereotypePackageName};
<#if dtDefinition.entity || dtDefinition.fragment>
import io.vertigo.dynamo.domain.model.UID;
</#if>
<#if dtDefinition.containsAccessor()>
import io.vertigo.dynamo.domain.model.VAccessor;
</#if>	
<#if dtDefinition.containsEnumAccessor()>
import io.vertigo.dynamo.domain.model.EnumVAccessor;
</#if>
<#if dtDefinition.containsListAccessor()>
import io.vertigo.dynamo.domain.model.ListVAccessor;
</#if>	
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
<#list annotations(dtDefinition.dtDefinition) as annotation>
${annotation}
</#list>
public final class ${dtDefinition.classSimpleName} implements ${dtDefinition.stereotypeInterfaceName} {
	private static final long serialVersionUID = 1L;

	<#list dtDefinition.fields as dtField>
		<#if dtField.foreignKey>

			<#list annotations(dtField.association.definition) as annotation>
	${annotation}
			</#list>
			<#if dtField.association.targetStaticMasterData>
	private final EnumVAccessor<${dtField.association.returnType}, ${dtField.association.returnType}Enum> ${dtField.upperCamelCaseName?uncap_first}Accessor = new EnumVAccessor<>(${dtField.association.returnType}.class, "${dtField.association.role}", ${dtField.association.returnType}Enum.class);
			<#else>
	private final VAccessor<${dtField.association.returnType}> ${dtField.upperCamelCaseName?uncap_first}Accessor = new VAccessor<>(${dtField.association.returnType}.class, "${dtField.association.role}");
			</#if>
		<#else>
	private ${dtField.javaType} ${dtField.upperCamelCaseName?uncap_first};
		</#if>
	</#list>
	<#list dtDefinition.associations as association>
		<#if association.multiple>
			<#if (association.simple && association.navigable) || !association.simple >

			<#list annotations(association.definition) as annotation>
	${annotation}
			</#list>
	private final ListVAccessor<${association.returnType}> ${association.role?uncap_first}Accessor = new ListVAccessor<>(this, "${association.urn}", "${association.role}");
			</#if>
		</#if>
	</#list>
	<#if dtDefinition.entity>

	/** {@inheritDoc} */
		<#list annotations("UID") as annotation>
	${annotation}
		</#list>
	@Override
	public UID<${dtDefinition.classSimpleName}> getUID() {
		return UID.of(this);
	}
	</#if>
	<#if dtDefinition.fragment>

	/** {@inheritDoc} */
		<#list annotations("UID") as annotation>
	${annotation}
		</#list>
	@Override
	public UID<${dtDefinition.entityClassSimpleName}> getEntityUID() {
		return DtObjectUtil.createEntityUID(this); 
	}
	</#if>
	<#list dtDefinition.fields as dtField>
	<#if dtField.foreignKey>
	
	/**
	 * Champ : ${dtField.type}.
	 * Récupère la valeur de la propriété '${dtField.display}'.
	 * @return ${dtField.javaTypeLabel} ${dtField.upperCamelCaseName?uncap_first}<#if dtField.required> <b>Obligatoire</b></#if>
	 */
		<#list annotations(dtField) as annotation>
	${annotation}
		</#list>
	public ${dtField.javaType} get${dtField.upperCamelCaseName}() {
		return (${dtField.javaType})  ${dtField.upperCamelCaseName?uncap_first}Accessor.getId();
	}

	/**
	 * Champ : ${dtField.type}.
	 * Définit la valeur de la propriété '${dtField.display}'.
	 * @param ${dtField.upperCamelCaseName?uncap_first} ${dtField.javaTypeLabel}<#if dtField.required> <b>Obligatoire</b></#if>
	 */
	public void set${dtField.upperCamelCaseName}(final ${dtField.javaType} ${dtField.upperCamelCaseName?uncap_first}) {
		${dtField.upperCamelCaseName?uncap_first}Accessor.setId(${dtField.upperCamelCaseName?uncap_first});
	}
	<#else>
	
	/**
	 * Champ : ${dtField.type}.
	 * Récupère la valeur de la propriété '${dtField.display}'.
	 * @return ${dtField.javaTypeLabel} ${dtField.upperCamelCaseName?uncap_first}<#if dtField.required> <b>Obligatoire</b></#if>
	 */
		<#list annotations(dtField) as annotation>
	${annotation}
		</#list>
	public ${dtField.javaType} get${dtField.upperCamelCaseName}() {
		return ${dtField.upperCamelCaseName?uncap_first};
	}

	/**
	 * Champ : ${dtField.type}.
	 * Définit la valeur de la propriété '${dtField.display}'.
	 * @param ${dtField.upperCamelCaseName?uncap_first} ${dtField.javaTypeLabel}<#if dtField.required> <b>Obligatoire</b></#if>
	 */
	public void set${dtField.upperCamelCaseName}(final ${dtField.javaType} ${dtField.upperCamelCaseName?uncap_first}) {
		this.${dtField.upperCamelCaseName?uncap_first} = ${dtField.upperCamelCaseName?uncap_first};
	}
	</#if>
	</#list>
	<#list dtDefinition.dtComputedFields as dtField>
	
	/**
	 * Champ : ${dtField.type}.
	 * Récupère la valeur de la propriété calculée '${dtField.display}'.
	 * @return ${dtField.javaTypeLabel} ${dtField.upperCamelCaseName?uncap_first}<#if dtField.required> <b>Obligatoire</b></#if>
	 */
		<#list annotations(dtField) as annotation>
	${annotation}
		</#list>
	public ${dtField.javaType} get${dtField.upperCamelCaseName}() {
		${dtField.javaCode}
	}
	</#list>
	<#if dtDefinition.associations?has_content>
		<#list dtDefinition.associations as association>
			<#if !association.multiple>

 	/**
	 * Association : ${association.label}.
	 * @return l'accesseur vers la propriété '${association.label}'
	 */
	<#list annotations('transientField') as annotation>
	${annotation}
	</#list>
		<#if association.targetStaticMasterData>
	public EnumVAccessor<${association.returnType}, ${association.returnType}Enum> ${association.role?uncap_first}() {
		<#else>
	public VAccessor<${association.returnType}> ${association.role?uncap_first}() {
		</#if>
		return ${association.upperCamelCaseFkFieldName?uncap_first}Accessor;
	}
				<#if association.navigable>
	
	@Deprecated
	<#list annotations('transientField') as annotation>
	${annotation}
	</#list>
	public ${association.returnType} get${association.role?cap_first}() {
		// we keep the lazyness
		if (!${association.upperCamelCaseFkFieldName?uncap_first}Accessor.isLoaded()) {
			${association.upperCamelCaseFkFieldName?uncap_first}Accessor.load();
		}
		return ${association.upperCamelCaseFkFieldName?uncap_first}Accessor.get();
	}

	/**
	 * Retourne l'UID: ${association.label}.
	 * @return UID de l'association
	 */
	@Deprecated
	<#list annotations('transientField') as annotation>
	${annotation}
	</#list>
	public io.vertigo.dynamo.domain.model.UID<${association.returnType}> get${association.role?cap_first}UID() {
		return ${association.upperCamelCaseFkFieldName?uncap_first}Accessor.getUID();
	}
				</#if>
		<#elseif association.navigable ><#-- multiple and navigable -->

	/**
	 * Association : ${association.label}.
	 * @return l'accesseur vers la propriété '${association.label}'
	 */
	<#list annotations('transientField') as annotation>
	${annotation}
	</#list>
	public ListVAccessor<${association.returnType}> ${association.role?uncap_first}() {
		return ${association.role?uncap_first}Accessor;
	}
	
	/**
	 * Association : ${association.label}.
	 * @return DtList de ${association.returnType}
	 */
	@Deprecated
	<#list annotations('transientField') as annotation>
	${annotation}
	</#list>
	public io.vertigo.dynamo.domain.model.DtList<${association.returnType}> get${association.role?cap_first}List() {
		// we keep the lazyness
		if (!${association.role?uncap_first}Accessor.isLoaded()) {
			${association.role?uncap_first}Accessor.load();
		}
		return ${association.role?uncap_first}Accessor.get();
	}

	/**
	 * Association UID: ${association.label}.
	 * @return UID de l'association
	 */
	@Deprecated	
	<#list annotations('transientField') as annotation>
	${annotation}
	</#list>		
	public io.vertigo.dynamo.domain.metamodel.association.DtListURIFor<#if association.simple>Simple<#else>NN</#if>Association get${association.role?cap_first}DtListURI() {
		return (io.vertigo.dynamo.domain.metamodel.association.DtListURIFor<#if association.simple>Simple<#else>NN</#if>Association) ${association.role?uncap_first}Accessor.getDtListURI();
	}
			</#if>
		</#list>
	</#if>
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
